### ISSUE TITLE
Overloads while field is an array allow string queries

### ISSUE THREAD

**Issue by patroza** [effect-app/libs#114]
```ts
  type Some = {
    readonly some: string[]
  }
  const base = make<Some>()
  const bad = base.pipe(where("some", "contains", "a")) // "startsWith" | "endsWith" | "contains" | "notContains" | "notStartsWith" | "notEndsWith"
  const good = base.pipe(where("some", "includes", "a"))
  const good2 = base.pipe(where("some", "includes-any", ["a"]))
```

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Update the OtherOps type to include 'includes' and 'includes-any' operations, and remove 'contains' operation to match the GitHub issue criteria.

I also created pull request: https://github.com/effect-app/libs/pull/118


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
